@base_uri=http://localhost:5555/api
@username=admin
@password=secret


###
GET {{base_uri}}/workers
Authorization: Basic {{username}}:{{password}}

###
GET {{base_uri}}/task/types
Authorization: Basic {{username}}:{{password}}

###
GET {{base_uri}}/tasks
Authorization: Basic {{username}}:{{password}}

###
POST {{base_uri}}/task/send-task/add
Authorization: Basic {{username}}:{{password}}
Accept:application/json

{
    "args": [2,5]
}

###
POST {{base_uri}}/task/send-task/foo
Authorization: Basic {{username}}:{{password}}
Accept:application/json

{
    "args": ["hello"]
}

###
POST {{base_uri}}/task/async-apply/add
Authorization: Basic {{username}}:{{password}}
Accept:application/json

{
    "args": [22,26],
    "task_id": "some-id:003",
    "eta": "2020-10-28 07:45:00.000"
    
}

###
POST {{base_uri}}/task/async-apply/add
Authorization: Basic {{username}}:{{password}}
Accept:application/json

{
    "args": [1,26],
    "countdown": 30
    
}


###
GET  {{base_uri}}/task/result/some-id:003
Authorization: Basic {{username}}:{{password}}

###
GET {{base_uri}}/task/info/9c81bd1e-4259-40e3-8586-4e458b6dd094
Authorization: Basic {{username}}:{{password}}