version: '3.7'
services:
  flower:  
    image: mher/flower:0.9.5
    command: ["flower", "--basic_auth=admin:secret", "--broker=redis://redis-6.0:6379/0", "--result-backend=redis://redis-6.0:6379/0",  "--port=5555"]
    volumes:
        - "./data:/data"
    ports:
      - 5555:5555
    # external_links:
    #   - "redis:redis-6.0"
    networks:
      - default
      - redis_net

networks:
    redis_net:
      external: true